// Target sources array to change catname to "Luxury Watch"
const targetSources = [
    "https://wristifyreseller.cartpe.in/",
    "https://watchfactorys.cartpe.in/",
    "https://watchkart.cartpe.in/",
    "https://timepiece.cartpe.in/",
    "https://hypewrist.cartpe.in/"
];

const brand = {
    tissot: [
        "Tisso_t Chronometer",
        "Tisso_t Chronography",
        "Tisso_t Sun&amp;Moon",
        "Tisso_t Gentaleman",
        "Tisso_t Silicium",
        "Tisso_t Courtier",
        "Tisso_t Slim",
        "Tisso_t Choronography",
        "Tisso_t All",
        "Tiss Ot",
        "Tisso_t AAA",
        "Tisso_t Lelocle",
        "Tissot Tachymeter",
        "Tisso_t Date&amp;Day",
        "Tisso_t Leather",
        "Tissot Swiss",
        "Tissot Carson",
        "Tissot Date&amp;Day"
    ],
    omega: [
        "Omeg_a Sun&amp;Moon",
        "Omeg_a S_Watch",
        "Omeg_a World",
        "Omeg_a Leather",
        "Omega Co-Axial",
        "Omegaa Ultra",
        "Omega Soeedmaster",
        "Omegaa_aquaterra Black",
        "Omega Aquaterra",
        "Omega Neptune",
        "Omega Jupiter",
        "Omega Saturn",
        "Omega Mars",
        "Omega Mercury",
        "Omega Pluto",
        "Omega Uranus",
        "Omega Moon",
        "Omeg_a Seamster",
        "Omega Seamster",
        "Omega Master",
        "Seamaster Co-Axial",
        "Omega Earth"
    ],
    "graham": [
        "Graham Chronometer"
    ],
    "g-shock": [
        "G-Shock GMB2100",
        "G-Shock GM2300",
        "G-Shock GA2300",
        "G-Shock GM110",
        "G-Shock Royal",
        "Gshock King",
        "G-Shock GAB001",
        "G-Shock DW6900",
        "G-Shock GBD200",
        "G-Shock GM5600",
        "Gshock GMB5000",
        "G-Shock Rosegold",
        "Gshock Neon",
        "G-Shock G2100",
        "Gshock GMB5000",
        "G-Shock DW5600",
        "Gshock GMB5000",
        "Gshock GMB5000",
        "G-Shock DW560",
        "G-Shock Star",
        "G-Shock GA100",
        "G-Shock Prizam",
        "G-Shock GM5600",
        "G-Shock Jelly",
        "G-Shock GMW-B5000TCF-2",
        "G-Shock GMWB5000",
        "G-Shock DW5600",
    ],
    "Gucci": [
        "Gucc_i X",
        "Gucc_i G-Timeless",
        "Gucci_Automatic_Premiums_Watch",
        "GUCCI_LADIES_ROSE-WHITE",
        "Gucci Tiffany",
        "Gucci Uomo",
        "GUCCI BLUE",
        "GUCCI GREEN",
        "Guccii G",
        "Gucci Print",
    ],
    rolex: [
        "Role_x Zoom",
        "Role_x Skydewller",
        "Role_x Labenior",
        "Role_x Gold",
        "Role_x Chronography",
        "Role_x Dat/Date",
        "Role_x Day/Date",
        "Rolex Date-Just",
        "Rolex Sea-Dweller",
        "Rolex Arabic",
        "Rolex Date-Just",
        "Rolex Rainbow GOLD",
        "Rolex Day-Date Working",
        "Rolex Datejust Blue",
        "Rolex 1908",
        "Role_x Black",
        "Rolex Celini",
        "Rolexx YachtMaster",
        "Rolexx Label",
        "Rolexx Yatchmaster",
        "Rolexx Yatchmaster",
        "Role_x 2024",
        "Role_x Yatchtmaster",
        "Rolez Yachtmaster",
        "Rolex Sea Master",
        "Rolex Skydeweller"
    ],
    "ulysse nardin": [
        "ULYSSENARDIN_AUTO",
        "ULYSSENARDIN_AUTO_BLACK",
        "ULYSSENARDIN PREMIUM",
        "ULYSSE_NARDIN AUTOMATIC",
        "ULYSS NARDIN"
    ],
    "Rado": [
        "Rad_o Florenceo",
        "Rad_o Square",
        "Rado Swiss",
        "Rado Quartz",
        "Rad_o Timeline",
        "Rado Timeline",
        "RAD_O SWISS",
        "RAD_O MENS",
        "RADO Arebic",
        "Rad_o Timeline",
        "Rado Jublie",
        "RADO QURATZ",
        "Rado Tachymeter",
        "Rado Hyperchome",
        "Rado Swiss",
        "RAD_O SLIM"
    ],
    "Longines": [
        "Longine_s Slimmest",
        "Longines GMT",
        "Longines Master",
        "Longines 30",
        "Longines 30Bar",
        "Longinees Conquest"
    ],
    "Patek Philippe": [
        "Pate_k Philipe",
        "Patek Aquanot",
        "Patek _",
        "Pate_k Phillippe",
        "Patek Philips",
        "Pate_k Phillippe",
        "Patek Aquanot",
        "Patek _",
        "Pate_k Phillippe",
        "Patek Philips",
        "Pate_k Philipe",
        "Patek Aquanot",
        "Patek _",
        "Pate_k Phillippe",
        "Patek Philips",
        "Pate_k Philipe",
        "Patek Aquanot",
        "Patek _",
        "Pate_k Phillippe",
        "Patek Philips",
        "Patek Aquanot",
        "Patek _",
        "Patek Philips",
        "Pate_k Philipe",
        "Patek Aquanot",
        "Patek _",
        "Pate_k Phillippe",
        "Patek Philips",
        "Pate_k Philipe",
        "Patek Aquanot",
        "Patek _",
        "Pate_k Phillippe",
        "Patek Philips",
        "Pate_k Philipe",
        "Patek Aquanot",
        "Patek _",
        "Pate_k Phillippe",
        "Patek Philips",
        "Patek Aquanot",
        "Patek _",
        "Patek Philips",
        "Pate_k Philipe",
        "Patek Aquanot",
        "Patek _",
        "Pate_k Phillippe",
        "Patek Philips",
        "Pate_k Philipe",
        "Patek Aquanot",
        "Pate_k Phillippe",
        "Patek Philips",
        "Patek Aquanot",
        "Patek _",
        "Patek Philips",
        "Pate_k Philipe",
        "Patek Aquanot",
        "Patek _",
        "Pate_k Phillippe",
        "Patek Philips",
        "Pate_k Philipe",
        "Patek Aquanot",
        "Pate_k Phillippe",
        "Patek Philips",
        "Patek Aquanot",
        "Patek _",
        "Patek Philips",
        "Pate_k Philipe",
        "Patek Aquanot",
        "Patek _",
        "Pate_k Phillippe",
        "Patek Philips",
        "Pate_k Philipe",
        "Patek Aquanot",
        "Pate_k Phillippe",
        "Patek Philips",
        "Patek Aquanot",
        "Patek _",
        "Patek Philips",
        "Pate_k Philipe",
        "Patek Aquanot",
        "Patek _",
        "Pate_k Phillippe",
        "Patek Philips",
        "Pate_k Philipe",
        "Patek Aquanot",
        "Pate_k Phillippe",
        "Patek Philips",
        "Patek Aquanot",
        "Patek _",
        "Patek Philips",
        "Pate_k Philipe",
        "Patek Aquanot",
        "Patek _",
        "Pate_k Phillippe",
        "Patek Philips",
        "Pate_k Philipe",
        "Patek Aquanot",
        "Pate_k Phillippe",
        "Patek Philips"
    ],

    fossil: [],
    casio: [],
    citizen: [],
    versace: [],
    movado: [],
    edifice: [],
    emporio: [],
    bronson: [],
    exchange: [],
    jacobCo: [],
    tommyHilfiger: [],
    diesel: [],
    hublot: [],
    audemarsPiguet: [],
    armani: [],
    bvlgari: [],
    swatch: [],
    franckMuller: [],
    corum: [],
    mauriceLacroix: [],
    iwc: [],
    tagHeuer: [],
    oris: [],
    breitling: [],
    danielWellington: [],
    invicta: [],
    gc: [],
    michaelKors: [],
    coach: [],
    usPolo: [],
    fendi: [],
    hermes: [],
    cartier: [],
    montblanc: [],
    tudor: [],
    panerai: [],
    ferragamo: [],
    seiko: [],
    chanel: [],
    bellRoss: [],
    boss: [],
    globetrottter: [],
    rogerDubuis: [],
    sevenfriday: [],
    citizenPromaster: [],
    others: []
};
















export function updateProductCategory(product) {
    // Check if the productFetchedFrom matches any of the target sources
    if (targetSources.includes(product.productFetchedFrom)) {
        product.catName = 'Luxury Watch'; // Update category to 'Luxury Watch'
    }

    return product;
}

